### ISSUE TITLE
Agree on appropriate algorithm to export

### ISSUE THREAD

**Issue by kezike** [digitalbazaar/ecdsa-multikey#10]
@dlongley @gannan08 The WebCrypto API methods (e.g., [SubtleCrypto.generateKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey)) expect for ECDSA key operations to use the algorithm's `name` value of `ECDSA` and its `namedCurve` value that is one of {`P-256`, `P-384`, `P-521`}. However, the [cryptosuite library](https://github.com/digitalbazaar/ecdsa-2019-cryptosuite) expects us to use the curve name (e.g., `P-256`) as the algorithm name. At the moment, `createSigner` and `createVerifier` export an `algorithm` property with the value of `ECDSA`. I believe this needs to be changed to the value of the appropriate curve name in order to match the semantics of the cryptosuite library. Thoughts?

**Comment by gannan08** [comment]
The algorithm for the cryptosuite will be `P-256`. The `createSigner` and `createVerifier` should export the specific curve name as the algorithm instead of `ECDSA`.

**Comment by kezike** [comment]
This issue was resolved by PR #11.
